default_platform(:ios)

# === iOS lanes ===
platform :ios do

  desc "Run tests"
  lane :test do
    scheme = ENV['SCHEME'] || "DefaultScheme"

    # Detección confiable de Swift Package o uso forzado vía IS_SPM=true
    is_package = ENV["IS_SPM"] == "true"

    if !is_package
      is_package = File.exist?(File.expand_path("../Package.swift")) &&
                   Dir.glob("../*.xcodeproj").empty? &&
                   Dir.glob("../*.xcworkspace").empty?
    end

    spm_root = File.expand_path("..")

    if is_package
      UI.message("✅ Detected pure Swift Package. Running with `swift test`...")
      Dir.chdir(spm_root) do
        sh "swift test"
      end
    else
      UI.message("📦 Detected Xcode project or workspace. Running with `xcodebuild`...")
      Dir.chdir(spm_root) do
        sh "xcodebuild -scheme #{scheme} -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4' clean test"
      end
    end
  end

  desc "Lint Swift code"
  lane :lint do
    if ENV["USE_SWIFTLINT"] == "true"
      sh "which swiftlint || brew install swiftlint"
      spm_root = File.expand_path("..")
      Dir.chdir(spm_root) do
        begin
          sh "swiftlint"
        rescue => ex
          UI.error("⚠️ SwiftLint encontró errores de estilo.")
          UI.message(ex.to_s)
          UI.important("🔍 Corrige los errores de estilo antes de hacer merge.")
        end
      end
    else
      UI.message("Lint deshabilitado o SwiftLint no requerido")
    end
  end

  desc "Build release"
  lane :build_release do
    scheme = ENV['SCHEME'] || "DefaultScheme"
    build_app(
      scheme: scheme,
      export_method: "ad-hoc"
    )
  end

  desc "CI lane"
  lane :ci do
    setup_tools
    test
    lint
  end

  desc "Instala herramientas necesarias si están habilitadas"
  lane :setup_tools do
    if ENV["USE_SWIFTLINT"] == "true"
      UI.message("Instalando SwiftLint...")
      sh "brew list swiftlint || brew install swiftlint"
    else
      UI.message("SwiftLint deshabilitado")
    end
  end

end # <- cierra plataforma iOS


# === Android lanes ===
platform :android do

  desc "Build release APK"
  lane :build_release do
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "./android"
    )
  end

  desc "Run tests"
  lane :test do
    gradle(
      task: "test",
      project_dir: "./android"
    )
  end

  desc "Distribuye a Firebase"
  lane :distribute_firebase do
    firebase_app_distribution(
      apk_path: "./android/app/build/outputs/apk/release/app-release.apk",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: "Versión automática desde Fastlane"
    )
  end

  desc "CI completo Android"
  lane :ci do
    test
    build_release
    distribute_firebase
  end

end
